apitest:
	curl -X POST \
		-H "Content-Type: application/json" \
		-d '{ \
			"username":"user123", \
			"password":"password123", \
			"courseId":1, \
			"courseName":"Sample Course", \
		 	"courseMetaData":"Sample Metadata", \
		 	"courseVideoLinks":["video1.mp4", "video2.mp4"]}' \
		http://localhost:8080/
